# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogClothes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DialogSearchPerson import Ui_Dialog

class Ui_Dialog_Clothes(object):

    def openWindow_SearchPerson(self):
        self.window_SearchPerson = QtWidgets.QMainWindow()
        self.ui = Ui_Dialog_Clothes()
        self.ui.setupUi(self.window_SearchPerson)
        self.window_SearchPerson.show()
    def setupUi(self, Dialog_Clothes):
        Dialog_Clothes.setObjectName("Dialog_Clothes")
        Dialog_Clothes.resize(918, 518)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_Clothes)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Type = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Type.setObjectName("label_Type")
        self.horizontalLayout.addWidget(self.label_Type)
        self.comboBox_Type = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.setItemText(0, "")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Type)
        self.label_Size = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Size.setObjectName("label_Size")
        self.horizontalLayout.addWidget(self.label_Size)
        self.comboBox_Size = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Size.setObjectName("comboBox_Size")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.comboBox_Size.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Size)
        self.label_FirstName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_FirstName.setObjectName("label_FirstName")
        self.horizontalLayout.addWidget(self.label_FirstName)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_LastName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_LastName.setObjectName("label_LastName")
        self.horizontalLayout.addWidget(self.label_LastName)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton_Search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.horizontalLayout.addWidget(self.pushButton_Search)
        self.listWidget = QtWidgets.QListWidget(Dialog_Clothes)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 781, 441))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_Clothes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(800, 60, 111, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_AssignCloth = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_AssignCloth.setObjectName("pushButton_AssignCloth")
        self.verticalLayout.addWidget(self.pushButton_AssignCloth)

        self.retranslateUi(Dialog_Clothes)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Clothes)

    def retranslateUi(self, Dialog_Clothes):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Clothes.setWindowTitle(_translate("Dialog_Clothes", "Dialog"))
        self.label_Type.setText(_translate("Dialog_Clothes", "Typ:"))
        self.comboBox_Type.setItemText(1, _translate("Dialog_Clothes", "Buty"))
        self.comboBox_Type.setItemText(2, _translate("Dialog_Clothes", "Koszulka"))
        self.comboBox_Type.setItemText(3, _translate("Dialog_Clothes", "Ogrodniczki"))
        self.comboBox_Type.setItemText(4, _translate("Dialog_Clothes", "Spodnie"))
        self.label_Size.setText(_translate("Dialog_Clothes", "Rozmiar:"))
        self.comboBox_Size.setItemText(0, _translate("Dialog_Clothes", "XXL"))
        self.comboBox_Size.setItemText(1, _translate("Dialog_Clothes", "XL"))
        self.comboBox_Size.setItemText(2, _translate("Dialog_Clothes", "L"))
        self.comboBox_Size.setItemText(3, _translate("Dialog_Clothes", "M"))
        self.comboBox_Size.setItemText(4, _translate("Dialog_Clothes", "S"))
        self.comboBox_Size.setItemText(5, _translate("Dialog_Clothes", "XS"))
        self.comboBox_Size.setItemText(6, _translate("Dialog_Clothes", "45"))
        self.comboBox_Size.setItemText(7, _translate("Dialog_Clothes", "44"))
        self.comboBox_Size.setItemText(8, _translate("Dialog_Clothes", "43"))
        self.label_FirstName.setText(_translate("Dialog_Clothes", "Imię:"))
        self.label_LastName.setText(_translate("Dialog_Clothes", "Nazwisko:"))
        self.pushButton_Search.setText(_translate("Dialog_Clothes", "Szukaj"))
        self.pushButton_AssignCloth.setText(_translate("Dialog_Clothes", "Przypisz osobie"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Dialog_Clothes = QtWidgets.QMainWindow()
    ui = Ui_Dialog_Clothes()
    ui.setupUi(Window_Dialog_Clothes)
    Window_Dialog_Clothes.show()
    sys.exit(app.exec_())